// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: runtime/src/mvalue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Ptr  *string `protobuf:"bytes,2,req,name=ptr" json:"ptr,omitempty"`
}

func (x *BaseObject) Reset() {
	*x = BaseObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_src_mvalue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseObject) ProtoMessage() {}

func (x *BaseObject) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_src_mvalue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseObject.ProtoReflect.Descriptor instead.
func (*BaseObject) Descriptor() ([]byte, []int) {
	return file_runtime_src_mvalue_proto_rawDescGZIP(), []int{0}
}

func (x *BaseObject) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *BaseObject) GetPtr() string {
	if x != nil && x.Ptr != nil {
		return *x.Ptr
	}
	return ""
}

type Vector3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z *float32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_src_mvalue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_src_mvalue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_runtime_src_mvalue_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type Vector2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_src_mvalue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_src_mvalue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_runtime_src_mvalue_proto_rawDescGZIP(), []int{2}
}

func (x *Vector2) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector2) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

// used when function is exported from go (Go::Runtime::ProtoToMValue)
type InternFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *string `protobuf:"bytes,1,req,name=resourceName" json:"resourceName,omitempty"`
	Id           *uint64 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
}

func (x *InternFunction) Reset() {
	*x = InternFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_src_mvalue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternFunction) ProtoMessage() {}

func (x *InternFunction) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_src_mvalue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternFunction.ProtoReflect.Descriptor instead.
func (*InternFunction) Descriptor() ([]byte, []int) {
	return file_runtime_src_mvalue_proto_rawDescGZIP(), []int{3}
}

func (x *InternFunction) GetResourceName() string {
	if x != nil && x.ResourceName != nil {
		return *x.ResourceName
	}
	return ""
}

func (x *InternFunction) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

// used when function is imported to go (Go::Runtime::MValueToProto(Bytes))
type ExternFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ptr *string `protobuf:"bytes,1,req,name=ptr" json:"ptr,omitempty"`
}

func (x *ExternFunction) Reset() {
	*x = ExternFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_src_mvalue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternFunction) ProtoMessage() {}

func (x *ExternFunction) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_src_mvalue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternFunction.ProtoReflect.Descriptor instead.
func (*ExternFunction) Descriptor() ([]byte, []int) {
	return file_runtime_src_mvalue_proto_rawDescGZIP(), []int{4}
}

func (x *ExternFunction) GetPtr() string {
	if x != nil && x.Ptr != nil {
		return *x.Ptr
	}
	return ""
}

type RGBA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R *uint32 `protobuf:"varint,1,req,name=r" json:"r,omitempty"`
	G *uint32 `protobuf:"varint,2,req,name=g" json:"g,omitempty"`
	B *uint32 `protobuf:"varint,3,req,name=b" json:"b,omitempty"`
	A *uint32 `protobuf:"varint,4,req,name=a" json:"a,omitempty"`
}

func (x *RGBA) Reset() {
	*x = RGBA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_src_mvalue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RGBA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RGBA) ProtoMessage() {}

func (x *RGBA) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_src_mvalue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RGBA.ProtoReflect.Descriptor instead.
func (*RGBA) Descriptor() ([]byte, []int) {
	return file_runtime_src_mvalue_proto_rawDescGZIP(), []int{5}
}

func (x *RGBA) GetR() uint32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

func (x *RGBA) GetG() uint32 {
	if x != nil && x.G != nil {
		return *x.G
	}
	return 0
}

func (x *RGBA) GetB() uint32 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

func (x *RGBA) GetA() uint32 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return 0
}

type MValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*MValue_NoneValue
	//	*MValue_NilValue
	//	*MValue_BoolValue
	//	*MValue_IntValue
	//	*MValue_UintValue
	//	*MValue_DoubleValue
	//	*MValue_StringValue
	//	*MValue_BaseObjectValue
	//	*MValue_InternFunctionValue
	//	*MValue_ExternFunctionValue
	//	*MValue_Vector3Value
	//	*MValue_RgbaValue
	//	*MValue_BytesValue
	//	*MValue_Vector2Value
	Value isMValue_Value `protobuf_oneof:"value"`
	// nested values
	List []*MValue `protobuf:"bytes,8,rep,name=list" json:"list,omitempty"`
	//repeated string dict = 9;
	Dict map[string]*MValue `protobuf:"bytes,9,rep,name=dict" json:"dict,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *MValue) Reset() {
	*x = MValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_src_mvalue_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MValue) ProtoMessage() {}

func (x *MValue) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_src_mvalue_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MValue.ProtoReflect.Descriptor instead.
func (*MValue) Descriptor() ([]byte, []int) {
	return file_runtime_src_mvalue_proto_rawDescGZIP(), []int{6}
}

func (m *MValue) GetValue() isMValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *MValue) GetNoneValue() bool {
	if x, ok := x.GetValue().(*MValue_NoneValue); ok {
		return x.NoneValue
	}
	return false
}

func (x *MValue) GetNilValue() bool {
	if x, ok := x.GetValue().(*MValue_NilValue); ok {
		return x.NilValue
	}
	return false
}

func (x *MValue) GetBoolValue() bool {
	if x, ok := x.GetValue().(*MValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *MValue) GetIntValue() int64 {
	if x, ok := x.GetValue().(*MValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *MValue) GetUintValue() uint64 {
	if x, ok := x.GetValue().(*MValue_UintValue); ok {
		return x.UintValue
	}
	return 0
}

func (x *MValue) GetDoubleValue() float64 {
	if x, ok := x.GetValue().(*MValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *MValue) GetStringValue() string {
	if x, ok := x.GetValue().(*MValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *MValue) GetBaseObjectValue() *BaseObject {
	if x, ok := x.GetValue().(*MValue_BaseObjectValue); ok {
		return x.BaseObjectValue
	}
	return nil
}

func (x *MValue) GetInternFunctionValue() *InternFunction {
	if x, ok := x.GetValue().(*MValue_InternFunctionValue); ok {
		return x.InternFunctionValue
	}
	return nil
}

func (x *MValue) GetExternFunctionValue() *ExternFunction {
	if x, ok := x.GetValue().(*MValue_ExternFunctionValue); ok {
		return x.ExternFunctionValue
	}
	return nil
}

func (x *MValue) GetVector3Value() *Vector3 {
	if x, ok := x.GetValue().(*MValue_Vector3Value); ok {
		return x.Vector3Value
	}
	return nil
}

func (x *MValue) GetRgbaValue() *RGBA {
	if x, ok := x.GetValue().(*MValue_RgbaValue); ok {
		return x.RgbaValue
	}
	return nil
}

func (x *MValue) GetBytesValue() []byte {
	if x, ok := x.GetValue().(*MValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (x *MValue) GetVector2Value() *Vector2 {
	if x, ok := x.GetValue().(*MValue_Vector2Value); ok {
		return x.Vector2Value
	}
	return nil
}

func (x *MValue) GetList() []*MValue {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MValue) GetDict() map[string]*MValue {
	if x != nil {
		return x.Dict
	}
	return nil
}

type isMValue_Value interface {
	isMValue_Value()
}

type MValue_NoneValue struct {
	NoneValue bool `protobuf:"varint,1,opt,name=noneValue,oneof"`
}

type MValue_NilValue struct {
	NilValue bool `protobuf:"varint,2,opt,name=nilValue,oneof"`
}

type MValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=boolValue,oneof"`
}

type MValue_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=intValue,oneof"`
}

type MValue_UintValue struct {
	UintValue uint64 `protobuf:"varint,5,opt,name=uintValue,oneof"`
}

type MValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=doubleValue,oneof"`
}

type MValue_StringValue struct {
	StringValue string `protobuf:"bytes,7,opt,name=stringValue,oneof"`
}

type MValue_BaseObjectValue struct {
	// special values
	BaseObjectValue *BaseObject `protobuf:"bytes,10,opt,name=baseObjectValue,oneof"`
}

type MValue_InternFunctionValue struct {
	InternFunctionValue *InternFunction `protobuf:"bytes,11,opt,name=internFunctionValue,oneof"`
}

type MValue_ExternFunctionValue struct {
	ExternFunctionValue *ExternFunction `protobuf:"bytes,12,opt,name=externFunctionValue,oneof"`
}

type MValue_Vector3Value struct {
	Vector3Value *Vector3 `protobuf:"bytes,13,opt,name=vector3Value,oneof"`
}

type MValue_RgbaValue struct {
	RgbaValue *RGBA `protobuf:"bytes,14,opt,name=rgbaValue,oneof"`
}

type MValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,15,opt,name=bytesValue,oneof"`
}

type MValue_Vector2Value struct {
	Vector2Value *Vector2 `protobuf:"bytes,16,opt,name=vector2Value,oneof"`
}

func (*MValue_NoneValue) isMValue_Value() {}

func (*MValue_NilValue) isMValue_Value() {}

func (*MValue_BoolValue) isMValue_Value() {}

func (*MValue_IntValue) isMValue_Value() {}

func (*MValue_UintValue) isMValue_Value() {}

func (*MValue_DoubleValue) isMValue_Value() {}

func (*MValue_StringValue) isMValue_Value() {}

func (*MValue_BaseObjectValue) isMValue_Value() {}

func (*MValue_InternFunctionValue) isMValue_Value() {}

func (*MValue_ExternFunctionValue) isMValue_Value() {}

func (*MValue_Vector3Value) isMValue_Value() {}

func (*MValue_RgbaValue) isMValue_Value() {}

func (*MValue_BytesValue) isMValue_Value() {}

func (*MValue_Vector2Value) isMValue_Value() {}

var File_runtime_src_mvalue_proto protoreflect.FileDescriptor

var file_runtime_src_mvalue_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x4d, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x32, 0x0a, 0x0a, 0x42, 0x61, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x74, 0x72, 0x22, 0x33, 0x0a, 0x07, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a,
	0x01, 0x7a, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x25, 0x0a, 0x07, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52,
	0x01, 0x79, 0x22, 0x44, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0e, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74,
	0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x70, 0x74, 0x72, 0x22, 0x3e, 0x0a, 0x04,
	0x52, 0x47, 0x42, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52,
	0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x01, 0x67,
	0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x01, 0x62, 0x12, 0x0c,
	0x0a, 0x01, 0x61, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x01, 0x61, 0x22, 0xa6, 0x06, 0x0a,
	0x06, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x6f,
	0x6e, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x6e, 0x69, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x69, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x75, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x09, 0x75, 0x69, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3e, 0x0a, 0x0f, 0x62,
	0x61, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x62, 0x61, 0x73, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4a, 0x0a, 0x13, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x13, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4a, 0x0a, 0x13, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x13,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4d, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x48, 0x00, 0x52, 0x0c, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x33, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x67,
	0x62, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x52, 0x47, 0x42, 0x41, 0x48, 0x00, 0x52, 0x09, 0x72,
	0x67, 0x62, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x32, 0x48, 0x00, 0x52, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x74, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64,
	0x69, 0x63, 0x74, 0x1a, 0x47, 0x0a, 0x09, 0x44, 0x69, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x62,
}

var (
	file_runtime_src_mvalue_proto_rawDescOnce sync.Once
	file_runtime_src_mvalue_proto_rawDescData = file_runtime_src_mvalue_proto_rawDesc
)

func file_runtime_src_mvalue_proto_rawDescGZIP() []byte {
	file_runtime_src_mvalue_proto_rawDescOnce.Do(func() {
		file_runtime_src_mvalue_proto_rawDescData = protoimpl.X.CompressGZIP(file_runtime_src_mvalue_proto_rawDescData)
	})
	return file_runtime_src_mvalue_proto_rawDescData
}

var file_runtime_src_mvalue_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_runtime_src_mvalue_proto_goTypes = []interface{}{
	(*BaseObject)(nil),     // 0: MValue.BaseObject
	(*Vector3)(nil),        // 1: MValue.Vector3
	(*Vector2)(nil),        // 2: MValue.Vector2
	(*InternFunction)(nil), // 3: MValue.InternFunction
	(*ExternFunction)(nil), // 4: MValue.ExternFunction
	(*RGBA)(nil),           // 5: MValue.RGBA
	(*MValue)(nil),         // 6: MValue.MValue
	nil,                    // 7: MValue.MValue.DictEntry
}
var file_runtime_src_mvalue_proto_depIdxs = []int32{
	0, // 0: MValue.MValue.baseObjectValue:type_name -> MValue.BaseObject
	3, // 1: MValue.MValue.internFunctionValue:type_name -> MValue.InternFunction
	4, // 2: MValue.MValue.externFunctionValue:type_name -> MValue.ExternFunction
	1, // 3: MValue.MValue.vector3Value:type_name -> MValue.Vector3
	5, // 4: MValue.MValue.rgbaValue:type_name -> MValue.RGBA
	2, // 5: MValue.MValue.vector2Value:type_name -> MValue.Vector2
	6, // 6: MValue.MValue.list:type_name -> MValue.MValue
	7, // 7: MValue.MValue.dict:type_name -> MValue.MValue.DictEntry
	6, // 8: MValue.MValue.DictEntry.value:type_name -> MValue.MValue
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_runtime_src_mvalue_proto_init() }
func file_runtime_src_mvalue_proto_init() {
	if File_runtime_src_mvalue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runtime_src_mvalue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_src_mvalue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_src_mvalue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_src_mvalue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_src_mvalue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_src_mvalue_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RGBA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_src_mvalue_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_runtime_src_mvalue_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*MValue_NoneValue)(nil),
		(*MValue_NilValue)(nil),
		(*MValue_BoolValue)(nil),
		(*MValue_IntValue)(nil),
		(*MValue_UintValue)(nil),
		(*MValue_DoubleValue)(nil),
		(*MValue_StringValue)(nil),
		(*MValue_BaseObjectValue)(nil),
		(*MValue_InternFunctionValue)(nil),
		(*MValue_ExternFunctionValue)(nil),
		(*MValue_Vector3Value)(nil),
		(*MValue_RgbaValue)(nil),
		(*MValue_BytesValue)(nil),
		(*MValue_Vector2Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runtime_src_mvalue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_src_mvalue_proto_goTypes,
		DependencyIndexes: file_runtime_src_mvalue_proto_depIdxs,
		MessageInfos:      file_runtime_src_mvalue_proto_msgTypes,
	}.Build()
	File_runtime_src_mvalue_proto = out.File
	file_runtime_src_mvalue_proto_rawDesc = nil
	file_runtime_src_mvalue_proto_goTypes = nil
	file_runtime_src_mvalue_proto_depIdxs = nil
}
