// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 01 Jul 2022 17:44:37 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "./build/out/capi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

