// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 01 Jul 2022 17:44:37 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package altcapi provides Go bindings for the handmade c-api of the go-module
*/
package altcapi
