// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: mvalue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Ptr  *string `protobuf:"bytes,2,req,name=ptr" json:"ptr,omitempty"`
}

func (x *BaseObject) Reset() {
	*x = BaseObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvalue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseObject) ProtoMessage() {}

func (x *BaseObject) ProtoReflect() protoreflect.Message {
	mi := &file_mvalue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseObject.ProtoReflect.Descriptor instead.
func (*BaseObject) Descriptor() ([]byte, []int) {
	return file_mvalue_proto_rawDescGZIP(), []int{0}
}

func (x *BaseObject) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *BaseObject) GetPtr() string {
	if x != nil && x.Ptr != nil {
		return *x.Ptr
	}
	return ""
}

type Vector3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z *float32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvalue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_mvalue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_mvalue_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type Vector2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvalue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_mvalue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_mvalue_proto_rawDescGZIP(), []int{2}
}

func (x *Vector2) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector2) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *string `protobuf:"bytes,1,req,name=resourceName" json:"resourceName,omitempty"`
	Id           *uint64 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
}

func (x *Function) Reset() {
	*x = Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvalue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_mvalue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_mvalue_proto_rawDescGZIP(), []int{3}
}

func (x *Function) GetResourceName() string {
	if x != nil && x.ResourceName != nil {
		return *x.ResourceName
	}
	return ""
}

func (x *Function) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type RGBA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R *uint32 `protobuf:"varint,1,req,name=r" json:"r,omitempty"`
	G *uint32 `protobuf:"varint,2,req,name=g" json:"g,omitempty"`
	B *uint32 `protobuf:"varint,3,req,name=b" json:"b,omitempty"`
	A *uint32 `protobuf:"varint,4,req,name=a" json:"a,omitempty"`
}

func (x *RGBA) Reset() {
	*x = RGBA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvalue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RGBA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RGBA) ProtoMessage() {}

func (x *RGBA) ProtoReflect() protoreflect.Message {
	mi := &file_mvalue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RGBA.ProtoReflect.Descriptor instead.
func (*RGBA) Descriptor() ([]byte, []int) {
	return file_mvalue_proto_rawDescGZIP(), []int{4}
}

func (x *RGBA) GetR() uint32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

func (x *RGBA) GetG() uint32 {
	if x != nil && x.G != nil {
		return *x.G
	}
	return 0
}

func (x *RGBA) GetB() uint32 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

func (x *RGBA) GetA() uint32 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return 0
}

type MValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// default values
	NoneValue   *bool    `protobuf:"varint,1,opt,name=noneValue" json:"noneValue,omitempty"`
	NilValue    *bool    `protobuf:"varint,2,opt,name=nilValue" json:"nilValue,omitempty"`
	BoolValue   *bool    `protobuf:"varint,3,opt,name=boolValue" json:"boolValue,omitempty"`
	IntValue    *int64   `protobuf:"varint,4,opt,name=intValue" json:"intValue,omitempty"`
	UintValue   *uint64  `protobuf:"varint,5,opt,name=uintValue" json:"uintValue,omitempty"`
	DoubleValue *float64 `protobuf:"fixed64,6,opt,name=doubleValue" json:"doubleValue,omitempty"`
	StringValue *string  `protobuf:"bytes,7,opt,name=stringValue" json:"stringValue,omitempty"`
	// nested values
	List []*MValue `protobuf:"bytes,8,rep,name=list" json:"list,omitempty"`
	Dict []string  `protobuf:"bytes,9,rep,name=dict" json:"dict,omitempty"`
	// special values
	BaseObjectValue *BaseObject `protobuf:"bytes,10,opt,name=baseObjectValue" json:"baseObjectValue,omitempty"`
	FunctionValue   *Function   `protobuf:"bytes,11,opt,name=functionValue" json:"functionValue,omitempty"`
	Vector3Value    *Vector3    `protobuf:"bytes,12,opt,name=vector3Value" json:"vector3Value,omitempty"`
	RgbaValue       *RGBA       `protobuf:"bytes,13,opt,name=rgbaValue" json:"rgbaValue,omitempty"`
	BytesValue      []byte      `protobuf:"bytes,14,opt,name=bytesValue" json:"bytesValue,omitempty"`
	Vector2Value    *Vector2    `protobuf:"bytes,15,opt,name=vector2Value" json:"vector2Value,omitempty"`
}

func (x *MValue) Reset() {
	*x = MValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvalue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MValue) ProtoMessage() {}

func (x *MValue) ProtoReflect() protoreflect.Message {
	mi := &file_mvalue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MValue.ProtoReflect.Descriptor instead.
func (*MValue) Descriptor() ([]byte, []int) {
	return file_mvalue_proto_rawDescGZIP(), []int{5}
}

func (x *MValue) GetNoneValue() bool {
	if x != nil && x.NoneValue != nil {
		return *x.NoneValue
	}
	return false
}

func (x *MValue) GetNilValue() bool {
	if x != nil && x.NilValue != nil {
		return *x.NilValue
	}
	return false
}

func (x *MValue) GetBoolValue() bool {
	if x != nil && x.BoolValue != nil {
		return *x.BoolValue
	}
	return false
}

func (x *MValue) GetIntValue() int64 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *MValue) GetUintValue() uint64 {
	if x != nil && x.UintValue != nil {
		return *x.UintValue
	}
	return 0
}

func (x *MValue) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *MValue) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

func (x *MValue) GetList() []*MValue {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MValue) GetDict() []string {
	if x != nil {
		return x.Dict
	}
	return nil
}

func (x *MValue) GetBaseObjectValue() *BaseObject {
	if x != nil {
		return x.BaseObjectValue
	}
	return nil
}

func (x *MValue) GetFunctionValue() *Function {
	if x != nil {
		return x.FunctionValue
	}
	return nil
}

func (x *MValue) GetVector3Value() *Vector3 {
	if x != nil {
		return x.Vector3Value
	}
	return nil
}

func (x *MValue) GetRgbaValue() *RGBA {
	if x != nil {
		return x.RgbaValue
	}
	return nil
}

func (x *MValue) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *MValue) GetVector2Value() *Vector2 {
	if x != nil {
		return x.Vector2Value
	}
	return nil
}

var File_mvalue_proto protoreflect.FileDescriptor

var file_mvalue_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x0a, 0x42, 0x61, 0x73, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74, 0x72, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x70, 0x74, 0x72, 0x22, 0x33, 0x0a, 0x07, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22,
	0x25, 0x0a, 0x07, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x3e, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x04, 0x52, 0x47, 0x42, 0x41, 0x12, 0x0c,
	0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01,
	0x67, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x01, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x01, 0x61, 0x22, 0xc2, 0x04, 0x0a, 0x06, 0x4d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6e, 0x6f, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x6e, 0x69, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x69, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x69, 0x63, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x69, 0x63, 0x74, 0x12,
	0x3c, 0x0a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0f, 0x62, 0x61,
	0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36, 0x0a,
	0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x0c, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x33, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x72, 0x67,
	0x62, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x52, 0x47, 0x42, 0x41, 0x52, 0x09, 0x72, 0x67, 0x62,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x0c, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62,
}

var (
	file_mvalue_proto_rawDescOnce sync.Once
	file_mvalue_proto_rawDescData = file_mvalue_proto_rawDesc
)

func file_mvalue_proto_rawDescGZIP() []byte {
	file_mvalue_proto_rawDescOnce.Do(func() {
		file_mvalue_proto_rawDescData = protoimpl.X.CompressGZIP(file_mvalue_proto_rawDescData)
	})
	return file_mvalue_proto_rawDescData
}

var file_mvalue_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mvalue_proto_goTypes = []interface{}{
	(*BaseObject)(nil), // 0: mvalue.BaseObject
	(*Vector3)(nil),    // 1: mvalue.Vector3
	(*Vector2)(nil),    // 2: mvalue.Vector2
	(*Function)(nil),   // 3: mvalue.Function
	(*RGBA)(nil),       // 4: mvalue.RGBA
	(*MValue)(nil),     // 5: mvalue.MValue
}
var file_mvalue_proto_depIdxs = []int32{
	5, // 0: mvalue.MValue.list:type_name -> mvalue.MValue
	0, // 1: mvalue.MValue.baseObjectValue:type_name -> mvalue.BaseObject
	3, // 2: mvalue.MValue.functionValue:type_name -> mvalue.Function
	1, // 3: mvalue.MValue.vector3Value:type_name -> mvalue.Vector3
	4, // 4: mvalue.MValue.rgbaValue:type_name -> mvalue.RGBA
	2, // 5: mvalue.MValue.vector2Value:type_name -> mvalue.Vector2
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mvalue_proto_init() }
func file_mvalue_proto_init() {
	if File_mvalue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mvalue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvalue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvalue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvalue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvalue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RGBA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvalue_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mvalue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mvalue_proto_goTypes,
		DependencyIndexes: file_mvalue_proto_depIdxs,
		MessageInfos:      file_mvalue_proto_msgTypes,
	}.Build()
	File_mvalue_proto = out.File
	file_mvalue_proto_rawDesc = nil
	file_mvalue_proto_goTypes = nil
	file_mvalue_proto_depIdxs = nil
}
